name: Run Script on INI File Update

on:
  push:
    branches:
      - main
      - development
    paths:
      - '**/*.ini'

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        pip install -r requirements.txt


    - name: Run appropriate script based on branch
      run: |
        echo "Current branch: ${{ github.ref }}"
        if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
          echo "Running main.py..."
          python main.py
        elif [[ "${{ github.ref }}" == "refs/heads/sandbox" ]]; then
          echo "Running sandbox.py..."
          python sandbox.py
        else
          echo "No script to run for this branch."
        fi
